apiVersion: v1
kind: Service
metadata:
  name: micro-proxy
  namespace: default
  labels:
    name: micro-proxy
    micro: runtime
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  selector:
    name: micro-proxy
    micro: runtime
  type: LoadBalancer
