name: Docker

on:
  pull_request
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository                          
      - uses: actions/checkout@v2                           
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Build and Push Docker Image                   
        uses: elgohr/Publish-Docker-Github-Action@2.12      
        with:                                               
          name: micro/go-micro                              
          username: ${{ secrets.DOCKER_USERNAME }}          
          password: ${{ secrets.DOCKER_PASSWORD }}          
