name: Run micro server integration tests
on: [push, pull_request]

jobs:

  test:
    name: Micro server integration tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go

    - name: Install Protoc
      uses: arduino/setup-protoc@master

    - name: Check out code
      uses: actions/checkout@v2 

    - name: Install micro
      run: |
        go install

    - name: Test micro server
      working-directory: ./test
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        # Retry the test suite up to 5 times due to occasional flakes.
        n=0
        until [ $n -ge 5 ]
        do
          echo "Try $n" && go clean -testcache && go test --tags=integration  -failfast -v ./... && break  # substitute your command here
          n=$[$n+1]
          sleep 15
        done
        