name: Run micro server integration tests on k8s (kind)
on:
  repository_dispatch:
    types: [my-event]

jobs:

  test:
    name: Micro server integration tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Kind
      uses: engineerd/setup-kind@v0.3.0

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: micro/micro
        event-type: my-event
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Apply tf files
      run: |
        bash scripts/launch-kind.sh

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go

    - name: Install Protoc
      uses: arduino/setup-protoc@master

    - name: Check out code
      uses: actions/checkout@v2 

    - name: Install micro
      run: |
        go install


