# This integration test is unfinished.
# The dream would be to ru the test suite after the tf apply
# but it's fairly flaky still.

name: K8s integration tests
on: [push]
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '00 00 * * *'

jobs:

  test:
    name: Micro server integration tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Kind
      uses: engineerd/setup-kind@v0.4.0
    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go

    # - name: Publish to Registry
    #   uses: elgohr/Publish-Docker-Github-Action@master
    #   with:
    #     name: micro/micro
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install the prerequisites
      run: |
        bash .github/workflows/kind-prereqs.sh
    - name: Install the platform
      run: |
        bash scripts/launch-kind.sh

    - name: Install failed, show platform logs
      if: ${{ failure() }}
      run: |
        kubectl get pods -n platform | awk '{print $1}' | xargs -n1 kubectl logs -n platform


