name: Run micro server integration tests on minikube
on: [push, pull_request]

jobs:

  test:
    name: Micro server integration tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Kind
      uses: engineerd/setup-kind@v0.3.0
    - name: Interact with the cluster
      run: kubectl get nodes

    - name: Apply resource tf files
      run: |
        cd platform/kubernetes/micro-resource
        export TF_VAR_resource_namespace=resource
        sed -i '/replicas/ s/3/1/g' nats.tf cockroachdb.tf etcd.tf
        terraform init; terraform apply -auto-approve

    - name: Apply platform tf files
      run: |
        ssh-keygen -b 2048 -t rsa -f /tmp/sshkey -q -N ""
        cd platform/kubernetes/micro-platform
        export TF_VAR_resource_namespace=platform
        export TF_VAR_micro_auth_private=$(cat /tmp/sshkey | base64 -w0)
        export TF_VAR_micro_auth_public=$(cat /tmp/sshkey.pub | base64 -w0)
        terraform init; terraform apply -auto-approve

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go

    - name: Install Protoc
      uses: arduino/setup-protoc@master

    - name: Check out code
      uses: actions/checkout@v2 

    - name: Install micro
      run: |
        go install


